<div class="print-header">
    <div class="print-logo">
        <img src="/assets/images/logo.jpeg" alt="Logo">
    </div>
    <div class="print-title" style="text-align:right;">
        <h1>Invoice</h1>
        <p style="font-size:1rem; font-weight:600; margin-top:.25rem;"><?= htmlspecialchars($invoice['number']) ?></p>
        <p style="margin-top:.25rem;"><span class="badge badge-<?= htmlspecialchars($invoice['status']) ?>"><?= htmlspecialchars($invoice['status']) ?></span></p>
    </div>
</div>

<div class="meta-grid">
    <div>
        <?php if ($invoice['contact_name']): ?>
        <div class="meta-block" style="margin-bottom:.75rem;">
            <label>Billed To</label>
            <p><?= htmlspecialchars($invoice['contact_name']) ?></p>
        </div>
        <?php endif; ?>
        <?php if ($invoice['project_name']): ?>
        <div class="meta-block">
            <label>Project</label>
            <p><?= htmlspecialchars($invoice['project_name']) ?></p>
        </div>
        <?php endif; ?>
    </div>
    <div style="text-align:right;">
        <div class="meta-block" style="margin-bottom:.75rem;">
            <label>Issue Date</label>
            <p><?= htmlspecialchars(date('M j, Y', strtotime($invoice['issue_date']))) ?></p>
        </div>
        <?php if ($invoice['due_date']): ?>
        <div class="meta-block">
            <label>Due Date</label>
            <p><?= htmlspecialchars(date('M j, Y', strtotime($invoice['due_date']))) ?></p>
        </div>
        <?php endif; ?>
    </div>
</div>

<table>
    <thead>
        <tr>
            <th>Description</th>
            <th class="right" style="width:80px;">Qty</th>
            <th class="right" style="width:110px;">Unit Price</th>
            <th class="right" style="width:100px;">Amount</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($items as $item): ?>
        <tr>
            <td><?= htmlspecialchars($item['description']) ?></td>
            <td class="right"><?= htmlspecialchars($item['quantity']) ?></td>
            <td class="right"><?= number_format($item['unit_price'], 2) ?></td>
            <td class="right"><?= number_format($item['amount'], 2) ?></td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>

<div class="totals-block">
    <div class="totals-inner">
        <div><span style="color:#64748b;">Subtotal</span><span><?= number_format($totals['subtotal'], 2) ?></span></div>
        <?php if ($invoice['tax_rate'] > 0): ?>
        <div><span style="color:#64748b;">Tax (<?= $invoice['tax_rate'] ?>%)</span><span><?= number_format($totals['tax'], 2) ?></span></div>
        <?php endif; ?>
        <div class="grand"><span>Total</span><span><?= number_format($totals['total'], 2) ?></span></div>
    </div>
</div>

<?php if ($invoice['notes']): ?>
<div class="notes">
    <label>Notes</label>
    <p style="white-space:pre-line;"><?= htmlspecialchars($invoice['notes']) ?></p>
</div>
<?php endif; ?>

<div class="footer">Generated by ThomasCRM</div>
